### ISSUE TITLE
Multiple native modules failure.

### ISSUE THREAD

**Issue by kenOfYugen** [charto/nbind#30]
I have written two native modules using `nbind`.
Each module is exposed via an `index.js` file like so:
```javascript
var nbind = require('nbind');

var binding = nbind.init(__dirname);
var lib = binding.lib;

module.exports = lib
```
When I require one of them, they both work as expected. Whenever I require both of them at the same time, hell breaks loose.
```javascript
binaryTreesCPP = require('./benchmarks/binary-trees/native-cpp');
binaryTreesC = require('./benchmarks/binary-trees/native-c');
```
causes:
```
$ node bench.js 
/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:145
    binding.bind = lib.NBind.bind_value;
                            ^

TypeError: Cannot read property 'bind_value' of undefined
    at initNode (/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:145:29)
    at /home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:114:13
    at findCompiledModule (/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:78:13)
    at find (/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:92:13)
    at Object.init (/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/node_modules/nbind/dist/nbind.js:103:5)
    at Object.<anonymous> (/home/ken/Desktop/node-benchmarks/benchmarks/binary-trees/native-c/index.js:3:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by jjrv** [comment]
Looking into this now... Can you send a package of your current project or a similar setup?

**Comment by kenOfYugen** [comment]
Yeah sure. It's not a very clean setup since I am trying out various different  things.

[nbind-example.tar.gz](https://github.com/charto/nbind/files/542601/nbind-example.tar.gz)

`npm install` in `native-cpp` and `native-c` should build things. I'm afraid it might be linux only compatible not 100% certain.

**Comment by jjrv** [comment]
I made a minimal example reproducing the issue now. Node 4 gives the error you got and Node 6 crashes...

**Comment by kenOfYugen** [comment]
I forgot to mention it, I'm using Node @6.9.1 on Linux.

**Comment by jjrv** [comment]
I think this is now fixed in the `develop` branch:

https://github.com/charto/nbind/tree/develop

Can you verify? I can't get your example to work (`run` and `boost::system` are not found when loading the addon due to some linker parameter issue).

**Comment by kenOfYugen** [comment]
@jjrv great job 👍 
I can confirm that after building everything up, `develop` branch has fixed the issue!
Wish I was more fluent in C++ to help you out more, but I'm getting there. Keep up the good work!
