### ISSUE TITLE
nbind::cbFunction & works, but not nbind::cbFunction const &

### ISSUE THREAD

**Issue by arcanis** [charto/nbind#49]
As the title says, it seems something bad happens when passing a const ref as parameter of a function. I get the following error:

```
Error: Unbound type const 4419? & in TextLayout.setCharacterGetter
    at reportProblem (/home/arcanis/text-formatter/build/Release/nbind.js:1:36937)
    at getComplexType (/home/arcanis/text-formatter/build/Release/nbind.js:1:37591)
    at getComplexType (/home/arcanis/text-formatter/build/Release/nbind.js:1:37688)
    at Object.getComplexType (/home/arcanis/text-formatter/build/Release/nbind.js:1:37688)
    at /home/arcanis/text-formatter/build/Release/nbind.js:1:69302
    at Array.map (native)
    at Object.getTypes (/home/arcanis/text-formatter/build/Release/nbind.js:1:69250)
    at Object.makeMethodCaller (/home/arcanis/text-formatter/build/Release/nbind.js:1:89372)
    at BindClass.registerMethods (/home/arcanis/text-formatter/build/Release/nbind.js:1:76888)
    at BindClass.registerSuperMethods (/home/arcanis/text-formatter/build/Release/nbind.js:1:77416)
```

**Comment by jjrv** [comment]
Using a `const cbFunction &` would also require its `call` method to be `const`, but JavaScript has no such concept so at some point it needs to be removed using `const_cast`. I think this makes the `const` qualifier of a `cbFunction` ultimately meaningless and possibly misleading.

**Comment by arcanis** [comment]
Hm that makes sense, I see, thanks.

**Comment by jjrv** [comment]
I misdiagnosed a compiler error and spoke too soon. The `const` is only promising that the `cbFunction` wrapper itself won't change. That is guaranteed anyway. I'll fix this.

**Comment by jjrv** [comment]
OK fixed in master.
